In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score,mean_squared_error
from math import sqrt
df = pd.read_csv('Aspect_AjA_sent.csv',sep=',')
df = df.drop(['Unnamed: 0'],axis=1)

In [2]:
cat_variables = df[['aspects', 'emotions']]
cat_dummies = pd.get_dummies(cat_variables, drop_first=True)
cat_dummies.head()

aspects_Linear then  aspects_arent brown  aspects_average actually  \
0                    0                    0                         0   
1                    0                    0                         0   
2                    0                    0                         0   
3                    0                    0                         0   
4                    0                    0                         0   

   aspects_average anymore  aspects_average back  aspects_average now  \
0                        0                     0                    0   
1                        0                     0                    0   
2                        0                     0                    1   
3                        0                     0                    0   
4                        0                     0                    0   

   aspects_average somewhere  aspects_average then  aspects_awful especially  \
0                          0                     0                         0   
1                          0                     0                         0   
2                          0                     0                         0   
3                          0                     0                         0   
4                          0                     0                         0   

   aspects_bad already  ...  aspects_youd just  aspects_youre actually  \
0                    0  ...                  0                       0   
1                    0  ...                  0                       0   
2                    0  ...                  0                       0   
3                    0  ...                  0                       0   
4                    0  ...                  0                       0   

   aspects_youre already  aspects_youre always  aspects_youre very  \
0                      0                     0                   0   
1                      0                     0                   0   
2                      0                     0                   0   
3                      0                     0                   0   
4                      0                     0                   0   

   aspects_youve already  emotions_Fear  emotions_Happy  emotions_Sad  \
0                      0              0               0             0   
1                      0              0               0             0   
2                      0              1               0             0   
3                      0              0               0             0   
4                      0              0               1             0   

   emotions_Surprise  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0  

[5 rows x 186 columns]

In [3]:
df = df.drop(['aspects', 'emotions'], axis=1)
df = pd.concat([cat_dummies,df], axis=1)
df.head()

aspects_Linear then  aspects_arent brown  aspects_average actually  \
0                    0                    0                         0   
1                    0                    0                         0   
2                    0                    0                         0   
3                    0                    0                         0   
4                    0                    0                         0   

   aspects_average anymore  aspects_average back  aspects_average now  \
0                        0                     0                    0   
1                        0                     0                    0   
2                        0                     0                    1   
3                        0                     0                    0   
4                        0                     0                    0   

   aspects_average somewhere  aspects_average then  aspects_awful especially  \
0                          0                     0                         0   
1                          0                     0                         0   
2                          0                     0                         0   
3                          0                     0                         0   
4                          0                     0                         0   

   aspects_bad already  ...  aspects_youre already  aspects_youre always  \
0                    0  ...                      0                     0   
1                    0  ...                      0                     0   
2                    0  ...                      0                     0   
3                    0  ...                      0                     0   
4                    0  ...                      0                     0   

   aspects_youre very  aspects_youve already  emotions_Fear  emotions_Happy  \
0                   0                      0              0               0   
1                   0                      0              0               0   
2                   0                      0              1               0   
3                   0                      0              0               0   
4                   0                      0              0               1   

   emotions_Sad  emotions_Surprise  frequency  Performance  
0             0                  0          1        87.39  
1             0                  0          1        87.39  
2             0                  0          1        87.39  
3             0                  0          1        87.39  
4             0                  0          1        87.39  

[5 rows x 188 columns]

In [4]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.10)

In [5]:
#using Sklearn library
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error 
from math import sqrt
rmse_val = [] #to store rmse values for different k
for K in range(21):
    K = K+1
    model = KNeighborsRegressor(n_neighbors = K, p=1, metric = 'manhattan')

    model.fit(X_train, y_train)  #fit the model
    
    pred=model.predict(X_test) #make prediction on test set
    error = sqrt(mean_squared_error(y_test,pred)) #calculate rmse
    rmse_val.append(error) #store rmse values
    print('RMSE value for k= ' , K , 'is:', error)

RMSE value for k=  1 is: 12.646700006429803
RMSE value for k=  2 is: 12.058397106973782
RMSE value for k=  3 is: 11.203902854866538
RMSE value for k=  4 is: 11.308264094992886
RMSE value for k=  5 is: 11.413439501883643
RMSE value for k=  6 is: 11.306364836618068
RMSE value for k=  7 is: 11.310203329539737
RMSE value for k=  8 is: 11.082908375476652
RMSE value for k=  9 is: 11.163831690405221
RMSE value for k=  10 is: 11.300803981645686
RMSE value for k=  11 is: 11.427035224186064
RMSE value for k=  12 is: 11.465435360438171
RMSE value for k=  13 is: 11.562228469797333
RMSE value for k=  14 is: 11.635142778489335
RMSE value for k=  15 is: 11.605503148146465
RMSE value for k=  16 is: 11.734611384191355
RMSE value for k=  17 is: 11.782960477807036
RMSE value for k=  18 is: 11.89705509083269
RMSE value for k=  19 is: 12.01062365189097
RMSE value for k=  20 is: 12.194288457047602
RMSE value for k=  21 is: 12.311334296741746


In [6]:
#using Sklearn library
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score, mean_squared_error
from math import sqrt
rmse_val = [] #to store rmse values for different k
train_s = []
for K in range(21):
    K = K+1
    model = KNeighborsRegressor(n_neighbors = K, p=1, metric = 'manhattan')

    model.fit(X_train, y_train)  #fit the model
    pred=model.predict(X_train)
    pred1=model.predict(X_test) #make prediction on test set
    train_error = mean_squared_error(y_train,pred)

    error = mean_squared_error(y_test,pred1) #calculate rmse

    print(K,' train error value = ',train_error,', test error value = ',error)

1  train error value =  0.0 , test error value =  159.93902105263157
2  train error value =  36.98961646341464 , test error value =  145.4049407894737
3  train error value =  66.4527584688347 , test error value =  125.52743918128657
4  train error value =  91.3375227515244 , test error value =  127.87683684210529
5  train error value =  92.84530109756098 , test error value =  130.26660126315792
6  train error value =  92.86374788279133 , test error value =  127.8338858187135
7  train error value =  98.50836173469392 , test error value =  127.92069935553177
8  train error value =  92.15341577743904 , test error value =  122.83085805921054
9  train error value =  97.05112755194219 , test error value =  124.63113801169591
10  train error value =  100.9407030548781 , test error value =  127.708170631579
11  train error value =  98.36440859201778 , test error value =  130.57713401478904
12  train error value =  97.9622799669716 , test error value =  131.45620800438599
13  train error value 

In [7]:
from sklearn.model_selection import GridSearchCV
params = {'n_neighbors':[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]}

knn = KNeighborsRegressor()

model = GridSearchCV(knn, params, cv=5)
model.fit(X_train,y_train)
model.best_params_



{'n_neighbors': 11}

In [8]:
from sklearn.model_selection import GridSearchCV
scoring={'R_squared':'r2','MSE':'neg_mean_squared_error'}
params = {'n_neighbors':list(range(1,21)),'metric':['euclidean','manhattan']}

knn = KNeighborsRegressor()
for key, value in scoring.items():
        grid = GridSearchCV(knn, params, cv=10, scoring=value)
        grid.fit(X,y)
        print(key)
        print('The Best Parameter:', grid.best_params_)
        if grid.best_score_ > 0:
            print('The Score:', grid.best_score_)
        else:
            print('The Score:', np.sqrt(abs(grid.best_score_)))
        print()

R_squared
The Best Parameter: {'metric': 'manhattan', 'n_neighbors': 20}
The Score: 1.9014922683708941

MSE
The Best Parameter: {'metric': 'euclidean', 'n_neighbors': 17}
The Score: 11.466640714466976



In [99]:
y_test = np.array(y_test)
X_test = np.array(X_test)
y_test[14]

89.05

In [100]:
model = KNeighborsRegressor(n_neighbors = 20, p=1, metric = 'euclidean')
model.fit(X_train, y_train)  #fit the model
 #make prediction on test set
#error = sqrt(mean_squared_error(y_test,pred)) #calculate rmse
#rmse_val.append(error) #store rmse values
#print('RMSE value for k= ' , K , 'is:', error)
ne = model.kneighbors([X_test[14]], 20 ,return_distance =False)
pred=model.predict([X_test[14]])
print(ne)

[[133   7  21  32   5  23  27  29  85  20  10  22  12  18  17  28  24   2
    4 161]]


In [101]:
pred

array([84.5605])

In [155]:
X_test[11]

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1], dtype=int64)

In [156]:
test = [[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0]]
test = pd.DataFrame(test)

In [157]:
#reverse get_dummies
x  = test.stack()
pd.Series(pd.Categorical(x[x!=0].index.get_level_values(1)))

0      5
1    182
dtype: category
Categories (2, int64): [5, 182]

In [181]:
# [[101   5  22 162  19   8  12  15  17   3   6   7  10  11  13  82  24   1  2  18]]
# [[  6  99  75  96  63  69  80  89  44  60  19  65  11  78  87  45  31 162 58 163]]
df.iloc[:, 163]

0      0
1      0
2      0
3      0
4      0
      ..
178    0
179    0
180    0
181    0
182    0
Name: aspects_variable not, Length: 183, dtype: uint8