In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score,mean_squared_error
from math import sqrt
df = pd.read_csv('combine_aspects.csv',sep=',')
df = df.drop(['Unnamed: 0'],axis=1)


In [2]:
cat_variables = df[['aspects', 'emotions']]
cat_dummies = pd.get_dummies(cat_variables, drop_first=True)
cat_dummies.head()

aspects_All right Yep  aspects_Alright already  \
0                      0                        0   
1                      0                        0   
2                      0                        0   
3                      0                        0   
4                      0                        0   

   aspects_Eleven binary Twelve  aspects_First okay Second  \
0                             0                          0   
1                             0                          0   
2                             0                          0   
3                             0                          0   
4                             0                          0   

   aspects_Just joking Im  aspects_Just put brackets  aspects_Linear then  \
0                       0                          0                    0   
1                       0                          0                    0   
2                       0                          0                    0   
3                       0                          0                    0   
4                       0                          0                    0   

   aspects_Literally step Ive  aspects_Names Yous aid  \
0                           0                       0   
1                           0                       0   
2                           0                       0   
3                           0                       0   
4                           0                       0   

   aspects_Not bubble sort  ...  aspects_youre right Youre  \
0                        0  ...                          0   
1                        0  ...                          0   
2                        0  ...                          0   
3                        0  ...                          0   
4                        0  ...                          0   

   aspects_youre right okay  aspects_youre right thats  \
0                         0                          0   
1                         0                          0   
2                         0                          0   
3                         0                          0   
4                         0                          0   

   aspects_youre taking points  aspects_youre very  aspects_youve already  \
0                            0                   0                      0   
1                            0                   0                      0   
2                            0                   0                      0   
3                            0                   0                      0   
4                            0                   0                      0   

   emotions_Fear  emotions_Happy  emotions_Sad  emotions_Surprise  
0              0               0             0                  0  
1              0               0             0                  0  
2              0               0             0                  0  
3              0               0             0                  0  
4              0               0             0                  0  

[5 rows x 760 columns]

In [3]:
df = df.drop(['aspects', 'emotions'], axis=1)
df = pd.concat([cat_dummies,df], axis=1)


In [4]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.10)

In [5]:
#using Sklearn library
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error 
from math import sqrt
rmse_val = [] #to store rmse values for different k
for K in range(21):
    K = K+1
    model = KNeighborsRegressor(n_neighbors = K, p=1, metric = 'manhattan')

    model.fit(X_train, y_train)  #fit the model
    
    pred=model.predict(X_test) #make prediction on test set
    error = sqrt(mean_squared_error(y_test,pred)) #calculate rmse
    rmse_val.append(error) #store rmse values
    print('RMSE value for k= ' , K , 'is:', error)

RMSE value for k=  1 is: 13.824679638431524
RMSE value for k=  2 is: 11.762444361969202
RMSE value for k=  3 is: 11.712960701368926
RMSE value for k=  4 is: 10.536560674872192
RMSE value for k=  5 is: 9.979197038154712
RMSE value for k=  6 is: 9.875589707760414
RMSE value for k=  7 is: 9.697391826868907
RMSE value for k=  8 is: 9.599218043554245
RMSE value for k=  9 is: 9.589896110355284
RMSE value for k=  10 is: 9.502716206571234
RMSE value for k=  11 is: 9.534885337957846
RMSE value for k=  12 is: 9.537509471782565
RMSE value for k=  13 is: 9.605445661674924
RMSE value for k=  14 is: 9.471448835939833
RMSE value for k=  15 is: 9.461890873424023
RMSE value for k=  16 is: 9.503145231701929
RMSE value for k=  17 is: 9.498295584146895
RMSE value for k=  18 is: 9.538834834762225
RMSE value for k=  19 is: 9.67141070963529
RMSE value for k=  20 is: 9.72185335559857
RMSE value for k=  21 is: 9.782980831299742


In [6]:
#using Sklearn library
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score, mean_squared_error
from math import sqrt
rmse_val = [] #to store rmse values for different k
train_s = []
for K in range(21):
    K = K+1
    model = KNeighborsRegressor(n_neighbors = K, p=1, metric = 'manhattan')

    model.fit(X_train, y_train)  #fit the model
    pred=model.predict(X_train)
    pred1=model.predict(X_test) #make prediction on test set
    train_error = mean_squared_error(y_train,pred)

    error = mean_squared_error(y_test,pred1) #calculate rmse

    print(K,' train error value = ',train_error,', test error value = ',error)

1  train error value =  0.0 , test error value =  191.12176710526316
2  train error value =  61.58669153225807 , test error value =  138.35509736842104
3  train error value =  76.0651671065494 , test error value =  137.19344839181286
4  train error value =  84.56663799486806 , test error value =  111.01911085526312
5  train error value =  92.83372472140766 , test error value =  99.58437352631577
6  train error value =  99.57449727517111 , test error value =  97.52727207602342
7  train error value =  100.90818993955355 , test error value =  94.03940824382387
8  train error value =  102.39753280333579 , test error value =  92.1449870476974
9  train error value =  102.62284252742481 , test error value =  91.9661074074074
10  train error value =  103.9713316217009 , test error value =  90.3016153026316
11  train error value =  104.29446227309084 , test error value =  90.91403840800349
12  train error value =  104.34438605001631 , test error value =  90.96408692434214
13  train error value 

In [8]:
from sklearn.model_selection import GridSearchCV
scoring={'R_squared':'r2','MSE':'neg_mean_squared_error'}
params = {'n_neighbors':list(range(1,21)),'metric':['euclidean','manhattan']}

knn = KNeighborsRegressor()
for key, value in scoring.items():
        grid = GridSearchCV(knn, params, cv=10, scoring=value)
        grid.fit(X,y)
        print(key)
        print('The Best Parameter:', grid.best_params_)
        if grid.best_score_ > 0:
            print('The Score:', grid.best_score_)
        else:
            print('The Score:', np.sqrt(abs(grid.best_score_)))
        print()

R_squared
The Best Parameter: {'metric': 'manhattan', 'n_neighbors': 19}
The Score: 0.3695343737194744

MSE
The Best Parameter: {'metric': 'manhattan', 'n_neighbors': 19}
The Score: 10.773616756544552



In [20]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score,mean_squared_error
from math import sqrt
model = KNeighborsRegressor(n_neighbors = 13, p=1, metric = 'manhattan')
model.fit(X_train, y_train)
pred=model.predict(X_test)
sc = model.score(X_train,y_train)
print('Train Score', sc)
sr = model.score(X_test,y_test)
print('Test Score', sr)
print('The r2_score for the model is:',r2_score(pred,y_test))
print('The RMSE for the model is:',sqrt(mean_squared_error(pred,y_test)))

Train Score 0.06366905935488165
Test Score -0.23260076132971763
The r2_score for the model is: -55.85535821685806
The RMSE for the model is: 11.619098249079787


In [ ]:
knn = KNeighborsRegressor(n_neighbors = 18)
from sklearn.model_selection import cross_val_score
scoring = 'neg_mean_absolute_error'
score = cross_val_score(knn,X_train,y_train, scoring=scoring, cv=5)
print(score)

In [19]:
from sklearn.model_selection import GridSearchCV
params = {'n_neighbors':[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]}

knn = KNeighborsRegressor()

model = GridSearchCV(knn, params, cv=5)
model.fit(X_train,y_train)
model.best_params_

{'n_neighbors': 13}

In [98]:
y_test = np.array(y_test)
X_test = np.array(X_test)
y_test[16]

87.48

In [99]:
X_test[16]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [103]:
model = KNeighborsRegressor(n_neighbors = 13, p=1, metric = 'euclidean')
model.fit(X_train, y_train)  #fit the model
ne = model.kneighbors([X_test[16]], 13, return_distance =False)
pred=model.predict([X_test[16]])
print(ne)

[[371   4  31  68  21  41  57  63  50  25  34   7   1]]


In [104]:
print(pred)

[81.63230769]


In [100]:
test = [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]]

In [101]:
test = pd.DataFrame(test)

In [102]:
x  = test.stack()
pd.Series(pd.Categorical(x[x!=0].index.get_level_values(1)))

0    372
1    756
dtype: category
Categories (2, int64): [372, 756]

In [122]:
# [[ 11  77  49  64  18  44  58  61   9 173   0   3  35]]
# [[ 16  26  13  23   2  12  17  22  84 349  10  15   8]]
# [[371   4  31  68  21  41  57  63  50  25  34   7   1]]

df.iloc[:,1]

0      0
1      0
2      0
3      0
4      0
      ..
753    0
754    0
755    0
756    0
757    0
Name: aspects_Alright already, Length: 758, dtype: uint8

In [45]:
df.iloc[:,759]

0      0
1      0
2      0
3      0
4      0
      ..
753    0
754    0
755    1
756    0
757    0
Name: emotions_Surprise, Length: 758, dtype: uint8